<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PengajuanBBSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pengajuan_bb = collect([
            [
                'id_pengajuan_bb' => 1,
                'approver' => 2,
                'submitter' => 2,
                'nama_barang' => 'Laptop Lenovo',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 5000000,
                'total_harga' => 250000000,
                'jumlah' => 50,
                'tgl' => Carbon::parse('2018-12-01'),
                'ruangan' => 'RGN001',
                'status_approval' => 'setuju',
                'tgl_approve' => Carbon::parse('2018-12-10'),
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 2,
                'approver' => 2,
                'submitter' => 3,
                'nama_barang' => 'Meja',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 5000000,
                'total_harga' => 50000000,
                'jumlah' => 10,
                'tgl' => Carbon::parse('2019-01-15'),
                'ruangan' => 'RGN001',
                'status_approval' => 'tidak',
                'tgl_approve' => null,
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 3,
                'approver' => 2,
                'submitter' => 1,
                'nama_barang' => 'Printer Epson',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 1500000,
                'total_harga' => 15000000,
                'jumlah' => 10,
                'tgl' => Carbon::parse('2019-02-20'),
                'ruangan' => 'RGN002',
                'status_approval' => 'setuju',
                'tgl_approve' => Carbon::parse('2019-02-25'),
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 4,
                'approver' => 3,
                'submitter' => 2,
                'nama_barang' => 'Kursi Kantor',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 2000000,
                'total_harga' => 40000000,
                'jumlah' => 20,
                'tgl' => Carbon::parse('2020-03-05'),
                'ruangan' => 'RGN003',
                'status_approval' => 'pending',
                'tgl_approve' => null,
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 5,
                'approver' => 1,
                'submitter' => 3,
                'nama_barang' => 'Mouse Logitech',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 300000,
                'total_harga' => 3000000,
                'jumlah' => 10,
                'tgl' => Carbon::parse('2020-04-10'),
                'ruangan' => 'RGN001',
                'status_approval' => 'setuju',
                'tgl_approve' => Carbon::parse('2020-04-15'),
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 6,
                'approver' => 2,
                'submitter' => 1,
                'nama_barang' => 'Monitor LG',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 3500000,
                'total_harga' => 105000000,
                'jumlah' => 30,
                'tgl' => Carbon::parse('2021-05-25'),
                'ruangan' => 'RGN002',
                'status_approval' => 'setuju',
                'tgl_approve' => Carbon::parse('2021-06-01'),
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 7,
                'approver' => 1,
                'submitter' => 2,
                'nama_barang' => 'Keyboard Razer',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 1500000,
                'total_harga' => 3000000,
                'jumlah' => 2,
                'tgl' => Carbon::parse('2021-07-07'),
                'ruangan' => 'RGN001',
                'status_approval' => 'setuju',
                'tgl_approve' => Carbon::parse('2021-07-15'),
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 8,
                'approver' => 3,
                'submitter' => 3,
                'nama_barang' => 'Proyektor Epson',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 8000000,
                'total_harga' => 16000000,
                'jumlah' => 2,
                'tgl' => Carbon::parse('2021-08-10'),
                'ruangan' => 'RGN003',
                'status_approval' => 'setuju',
                'tgl_approve' => Carbon::parse('2021-08-20'),
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 9,
                'approver' => 1,
                'submitter' => 2,
                'nama_barang' => 'Scanner Canon',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 2000000,
                'total_harga' => 4000000,
                'jumlah' => 2,
                'tgl' => Carbon::parse('2022-09-12'),
                'ruangan' => 'RGN002',
                'status_approval' => 'setuju',
                'tgl_approve' => Carbon::parse('2022-09-18'),
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 10,
                'approver' => 3,
                'submitter' => 3,
                'nama_barang' => 'Speaker JBL',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 1000000,
                'total_harga' => 5000000,
                'jumlah' => 5,
                'tgl' => Carbon::parse('2022-10-01'),
                'ruangan' => 'RGN001',
                'status_approval' => 'pending',
                'tgl_approve' => null,
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 11,
                'approver' => 1,
                'submitter' => 2,
                'nama_barang' => 'Hard Disk External',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 800000,
                'total_harga' => 8000000,
                'jumlah' => 10,
                'tgl' => Carbon::parse('2023-11-15'),
                'ruangan' => 'RGN002',
                'status_approval' => 'setuju',
                'tgl_approve' => Carbon::parse('2023-11-20'),
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 12,
                'approver' => 2,
                'submitter' => 1,
                'nama_barang' => 'Printer HP',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 2000000,
                'total_harga' => 10000000,
                'jumlah' => 5,
                'tgl' => Carbon::parse('2023-12-01'),
                'ruangan' => 'RGN001',
                'status_approval' => 'tidak',
                'tgl_approve' => null,
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 13,
                'approver' => 3,
                'submitter' => 2,
                'nama_barang' => 'Scanner Epson',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 3000000,
                'total_harga' => 15000000,
                'jumlah' => 5,
                'tgl' => Carbon::parse('2024-01-05'),
                'ruangan' => 'RGN003',
                'status_approval' => 'pending',
                'tgl_approve' => null,
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 14,
                'approver' => 1,
                'submitter' => 3,
                'nama_barang' => 'Keyboard Wireless',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 500000,
                'total_harga' => 5000000,
                'jumlah' => 10,
                'tgl' => Carbon::parse('2000-03-10'),
                'ruangan' => 'RGN001',
                'status_approval' => 'setuju',
                'tgl_approve' => Carbon::parse('2000-03-12'),
                'status_pembelian' => null,
            ],
            [
                'id_pengajuan_bb' => 15,
                'approver' => 2,
                'submitter' => 1,
                'nama_barang' => 'Mouse Wireless',
                'spesifikasi' => 'Lorem Ipsum',
                'harga_satuan' => 250000,
                'total_harga' => 1250000,
                'jumlah' => 5,
                'tgl' => Carbon::parse('2000-03-15'),
                'ruangan' => 'RGN002',
                'status_approval' => 'tidak',
                'tgl_approve' => null,
                'status_pembelian' => null,
            ],
        ]);
        $pengajuan_bb->each(fn ($m) => DB::table('pengajuan_bb')->insert($m));
    }
}
